// <auto-generated />
using Interview.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Interview.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Interview.Api.Models.Agent", b =>
                {
                    b.Property<int>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContactNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.HasKey("AgentId");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            AgentId = 1,
                            ContactNumber = 123453231,
                            Name = "john doe1"
                        },
                        new
                        {
                            AgentId = 2,
                            ContactNumber = 123453231,
                            Name = "john doe2"
                        },
                        new
                        {
                            AgentId = 3,
                            ContactNumber = 123453231,
                            Name = "john doe3"
                        },
                        new
                        {
                            AgentId = 4,
                            ContactNumber = 123453231,
                            Name = "john doe4"
                        },
                        new
                        {
                            AgentId = 5,
                            ContactNumber = 123453231,
                            Name = "john doe5"
                        },
                        new
                        {
                            AgentId = 6,
                            ContactNumber = 123453231,
                            Name = "john doe6"
                        },
                        new
                        {
                            AgentId = 7,
                            ContactNumber = 123453231,
                            Name = "john doe7"
                        },
                        new
                        {
                            AgentId = 8,
                            ContactNumber = 123453231,
                            Name = "john doe8"
                        },
                        new
                        {
                            AgentId = 9,
                            ContactNumber = 123453231,
                            Name = "john doe9"
                        },
                        new
                        {
                            AgentId = 10,
                            ContactNumber = 123453231,
                            Name = "john doe10"
                        },
                        new
                        {
                            AgentId = 11,
                            ContactNumber = 123453231,
                            Name = "john doe11"
                        },
                        new
                        {
                            AgentId = 12,
                            ContactNumber = 123453231,
                            Name = "john doe12"
                        },
                        new
                        {
                            AgentId = 13,
                            ContactNumber = 123453231,
                            Name = "john doe13"
                        },
                        new
                        {
                            AgentId = 14,
                            ContactNumber = 123453231,
                            Name = "john doe14"
                        },
                        new
                        {
                            AgentId = 15,
                            ContactNumber = 123453231,
                            Name = "john doe15"
                        },
                        new
                        {
                            AgentId = 16,
                            ContactNumber = 123453231,
                            Name = "john doe16"
                        },
                        new
                        {
                            AgentId = 17,
                            ContactNumber = 123453231,
                            Name = "john doe17"
                        },
                        new
                        {
                            AgentId = 18,
                            ContactNumber = 123453231,
                            Name = "john doe18"
                        },
                        new
                        {
                            AgentId = 19,
                            ContactNumber = 123453231,
                            Name = "john doe19"
                        },
                        new
                        {
                            AgentId = 20,
                            ContactNumber = 123453231,
                            Name = "john doe20"
                        },
                        new
                        {
                            AgentId = 21,
                            ContactNumber = 123453231,
                            Name = "john doe21"
                        },
                        new
                        {
                            AgentId = 22,
                            ContactNumber = 123453231,
                            Name = "john doe22"
                        },
                        new
                        {
                            AgentId = 23,
                            ContactNumber = 123453231,
                            Name = "john doe23"
                        },
                        new
                        {
                            AgentId = 24,
                            ContactNumber = 123453231,
                            Name = "john doe24"
                        },
                        new
                        {
                            AgentId = 25,
                            ContactNumber = 123453231,
                            Name = "john doe25"
                        },
                        new
                        {
                            AgentId = 26,
                            ContactNumber = 123453231,
                            Name = "john doe26"
                        },
                        new
                        {
                            AgentId = 27,
                            ContactNumber = 123453231,
                            Name = "john doe27"
                        },
                        new
                        {
                            AgentId = 28,
                            ContactNumber = 123453231,
                            Name = "john doe28"
                        },
                        new
                        {
                            AgentId = 29,
                            ContactNumber = 123453231,
                            Name = "john doe29"
                        },
                        new
                        {
                            AgentId = 30,
                            ContactNumber = 123453231,
                            Name = "john doe30"
                        },
                        new
                        {
                            AgentId = 31,
                            ContactNumber = 123453231,
                            Name = "john doe31"
                        },
                        new
                        {
                            AgentId = 32,
                            ContactNumber = 123453231,
                            Name = "john doe32"
                        },
                        new
                        {
                            AgentId = 33,
                            ContactNumber = 123453231,
                            Name = "john doe33"
                        },
                        new
                        {
                            AgentId = 34,
                            ContactNumber = 123453231,
                            Name = "john doe34"
                        },
                        new
                        {
                            AgentId = 35,
                            ContactNumber = 123453231,
                            Name = "john doe35"
                        },
                        new
                        {
                            AgentId = 36,
                            ContactNumber = 123453231,
                            Name = "john doe36"
                        },
                        new
                        {
                            AgentId = 37,
                            ContactNumber = 123453231,
                            Name = "john doe37"
                        },
                        new
                        {
                            AgentId = 38,
                            ContactNumber = 123453231,
                            Name = "john doe38"
                        },
                        new
                        {
                            AgentId = 39,
                            ContactNumber = 123453231,
                            Name = "john doe39"
                        },
                        new
                        {
                            AgentId = 40,
                            ContactNumber = 123453231,
                            Name = "john doe40"
                        },
                        new
                        {
                            AgentId = 41,
                            ContactNumber = 123453231,
                            Name = "john doe41"
                        },
                        new
                        {
                            AgentId = 42,
                            ContactNumber = 123453231,
                            Name = "john doe42"
                        },
                        new
                        {
                            AgentId = 43,
                            ContactNumber = 123453231,
                            Name = "john doe43"
                        },
                        new
                        {
                            AgentId = 44,
                            ContactNumber = 123453231,
                            Name = "john doe44"
                        },
                        new
                        {
                            AgentId = 45,
                            ContactNumber = 123453231,
                            Name = "john doe45"
                        },
                        new
                        {
                            AgentId = 46,
                            ContactNumber = 123453231,
                            Name = "john doe46"
                        },
                        new
                        {
                            AgentId = 47,
                            ContactNumber = 123453231,
                            Name = "john doe47"
                        },
                        new
                        {
                            AgentId = 48,
                            ContactNumber = 123453231,
                            Name = "john doe48"
                        },
                        new
                        {
                            AgentId = 49,
                            ContactNumber = 123453231,
                            Name = "john doe49"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
